server:
  servlet:
    contextPath: /prime-number-service

spring:
  application:
    name: prime-number-service

logging:
  level:
    root: info

management:
  security:
    enabled: false
  server:
    port: 8081
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: caches
